### ISSUE TITLE
URGENT-

### ISSUE THREAD

**Issue by adrianareis-1** [strangerstudios/pmpro-donations#14]
I uploaded and activated the Donations Add on.
I set my donation and custom field under my membership but the donations options does not display on the product. Please HELP! URGENT.

In the meantime I created a form using jot form until I solve the issue but I need help as soon as possible.

Thank you in advance for your prompt response.
URL - captainsforcleanwater.org

**Comment by andrewlimaza** [comment]
Sorry for only seeing this now - the best way to get support is on www.paidmembershipspro.com regarding issues.

We will be updating this plugin in the foreseeable future. Thank you for your patience.
