### ISSUE TITLE
Bug:  Undefined index: donation_dropdown in pmpro-donations.php on line 182

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-donations#24]
When price dropdown values is set the checkout page the following error is returned in the debug log `[30-Aug-2019 18:22:06 UTC] PHP Notice: Undefined index: donation_dropdown in /var/sites/public_html/wp/wp-content/plugins/pmpro-donations/pmpro-donations.php on line 182′

Temporary workaround is to check whether donation_dropdown is set.

`<?php if(!empty($pmprodon_allow_other) && isset($_REQUEST['donation_dropdown']) && $_REQUEST['donation_dropdown'] != 'other') { ?>`

**Comment by dparker1005** [comment]
Additional report of this on line 99:
`[04-May-2020 19:25:18 UTC] PHP Notice: Undefined index: donation_dropdown in /home/customer/www/website.com/public_html/wp/wp-content/plugins/pmpro-donations/includes/checkout.php on line 99`
