### ISSUE TITLE
Donations not being stored in order notes

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-donations#26]
Donations are not being stored in order notes. 

Tested this with Stripe as payment gateway.

**Comment by andrewlimaza** [comment]
This also includes not sending to the confirmation email and the invoice page.

**Comment by tictag** [comment]
The code referring to these functions is here: https://github.com/strangerstudios/pmpro-donations/blob/dev/includes/checkout.php#L290-L347

**Comment by dparker1005** [comment]
Fixed in v1.0
