### ISSUE TITLE
Donation option does not display on multiple membership checkout

### ISSUE THREAD

**Issue by shanagram** [strangerstudios/pmpro-donations#27]
If a membership with the donation option is selected along with any other paid or free membership in the same checkout action the donation option is not displayed (help text and donation field). This is likely caused by a conflict with the Multiple Memberships Per User plugin.

**Comment by andrewlimaza** [comment]
This should be resolved with PMPro V3.0+ as we have adjusted how MMPU handles checkouts and improved it's compatibility.
