### ISSUE TITLE
BUG: REST API request failed due to error.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-donations#30]
An error is being reported by "Site Health"  in WordPress when this plugin is activated.
as reported by user: https://www.paidmembershipspro.com/forums/topic/donations-add-on-causing-site-health-issue/

"The REST API request failed due to an error.
Error: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (http_request_failed) "

We were able to replicate in a number of server environments.

**Comment by dparker1005** [comment]
Will be resolved by #33
