### ISSUE TITLE
Bug: Strip slashes from Help Text

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-donations#31]
Steps to Recreate

- Create a new membership level with donations enabled
- Enter content in the Help Text Field with an apostrophe
- Save the level
- Help text will keep the slashes on the frontend and backend

Environment

- WordPress 5.4.1
- PMPro 2.3.2
- Donations Add-on 1.0

Expected Behavior

- Slashes should be stripped on apostrophes

**Comment by andrewlimaza** [comment]
We can use stripcslashes function to fix this :)

**Comment by kimcoleman** [comment]
Fixed / initial fix in https://github.com/strangerstudios/pmpro-donations/pull/32

**Comment by dparker1005** [comment]
#32 was merged in 1.1
