### ISSUE TITLE
Store donation amount in ordermeta

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-donations#37]
v2.5+ of Paid Memberships Pro introduces the `pmpro_membership_ordermeta` table. We should update this Add On to store the user's "donation amount" in the ordermeta. 

We would need to check the version of PMPro and make sure that the table is available before completely migrating to this method as the only place the data is stored. We can make the update to save the data in two places (order notes and ordermeta) for perhaps 1 year then update to only store in ordermeta.

This would also resolve issue #25

**Comment by tictag** [comment]
Great idea!

**Comment by ideadude** [comment]
We'd also then be able to add a donation column to the order CSV export.

**Comment by ideadude** [comment]
Some gists to add the donation amount to the order table and CSV export.

https://gist.github.com/kimwhite/257aa6b5be91513fbe32bb7caf023479

https://gist.github.com/kimwhite/19c72705673dd3dc4aec85ef6d5a71a0

**Comment by MaryOJob** [comment]
Example of the pmpro_get_price_parts filter here, please, to add the donation to the invoice and email invoice: https://gist.github.com/dparker1005/6dacc12fc71a05038ab70b950a288c3a

**Comment by dparker1005** [comment]
This change was made in 2.0.
