### ISSUE TITLE
ISSUE: Show billing fields when dropdown price is selected.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-donations#38]
The owner has 0 as the first dropdown option. When the user selects a price, payment fields do not appear until they reload the page.

Related to https://github.com/strangerstudios/pmpro-donations/issues/23 ?

**Comment by andrewlimaza** [comment]
Is the base level free or does it have a paid level? I've seen in the past that you cannot (on the fly) adjust the price as things happen on page load to load the payment gateway requirements and fields.
