### ISSUE TITLE
ISSUE/BUG: Donation not added to price If user includes $ sign 

### ISSUE THREAD

**Issue by ozsolarwind** [strangerstudios/pmpro-donations#40]
If the user includes a dollar sign, e.g. '$10' rather than '10', in the donation field the donation is not added to the payment.
Using Version 1.1.1:
In /includes/checkout.php:
line 224 '_$level->initial_payment = $level->initial_payment + $donation;_' fails if $donation starts with a $ sign.
I added a workaround after line 217:
_$donation = ltrim($donation, '$'); // remove any leading $ sign_

**Comment by dparker1005** [comment]
Thank you for this bug report! We have just merged a fix for this issue that will be released in the next update.
