### ISSUE TITLE
Donation input field autofilled by some web browsers.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-donations#45]
A user reported that in some cases the user's web browsers may autofill the donation input (text) field with parts of an address, e.g. zipcode, street number, etc., saved in the browser resulting in the user being charged for a donation value at checkout.

We could consider adding the HTML attribute `autocomplete="off"` for the text input field.

This could not be replicated during testing.

Moderators:  # 500040

**Comment by MaximilianoRicoTabo** [comment]
added suggested [fix](https://github.com/strangerstudios/pmpro-donations/pull/51/commits/eab3ee1c8a639ba88f7624d09ba11c0e973083ef)
