### ISSUE TITLE
Adding Help Text - extra p tags are added on each save of the level.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-donations#49]
When a site owner adds a message to the donation "Help Text" field on the Levels page, additional P tags are added on each save.

Example:
The entry `my custom message here` will change on each save.
After 3 saves of the level, it would look like this.
`<p><p><p>my custom message here</p></p></p>` 

https://capture.dropbox.com/BG9ipePR2J0kToP2

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/pmpro-donations/pull/51
