### ISSUE TITLE
Return from PayPal Express sets donations to 0.00

### ISSUE THREAD

**Issue by lok1728** [strangerstudios/pmpro-donations#6]
When returning from PayPal Express, the donation dropdown is disabled (which is correct) but the amount shows 0.00 even if there was a donation submitted.  It appears a REQUEST is used instead of SESSION.

LINE 167
`<option <?php selected($price, $_REQUEST['donation']);?> value="<?php echo esc_attr($price);?>"><?php echo pmpro_formatPrice((double)$price);?></option`

Updating to the below change fixes this issue.
`<option <?php selected($price, $_SESSION['donation']);?> value="<?php echo esc_attr($price);?>"><?php echo pmpro_formatPrice((double)$price);?></option>`

This is for version .3

**Comment by strangerstudios** [comment]
This has been fixed in a different way here https://github.com/strangerstudios/pmpro-donations/commit/2a266195971a966ac8f6ab27c70efaebb2b23525 and here https://github.com/strangerstudios/pmpro-donations/commit/efdc20d7d42925f1a1d3041186aa4d9e6b146367
